title: Bitcoin Miner Empire
description: Hunt for Bitcoin with your spotlight and build your mining empire
# For project sites hosted at https://<user>.github.io/<repo>
# set baseurl to the repository name (leading slash).
baseurl: "/Mytestwebsite"
# Set url to your GitHub Pages root
url: "https://tlushbough.github.io"
theme: minima
plugins:
  - jekyll-feed
